
[31m[2022-07-14 14:34:40,953] [Request.py:55] [Request:send_request] [ERROR]- unkown error[0m

[31m[2022-07-14 14:34:40,953] [Assert.py:49] [Assert:assert_in] [ERROR]- 用例：【查询任务列表】 实际结果: {'errCode': '0', 'errMsg': '用户未登录', 'success': False}不包含或部分包含预期结果：{'success': True}，用例不通过，请检查不匹配项![0m
