
[31m[2022-06-25 17:13:12,875] [Assert.py:49] [Assert:assert_in] [ERROR]- 用例：【查询任务列表】 实际结果: {'errCode': '0', 'errMsg': '用户未登录', 'success': False}不包含或部分包含预期结果：{'success': True}，用例不通过，请检查不匹配项![0m
